### ISSUE TITLE
House structure spawning

### ISSUE THREAD

**Issue by AminoX99** [comofastm/ArsTheurgia#3]
So the issue is that the house structure is always spawning above an astromine meteor thingy

Steps to reproduce:
1. download Ars Theurgia and Astromine (And the dependencys of both mods)
2. run the game
3. create a new world
4. Do /locate arstheurgia:[the house structure]
5. tp to that location and you will see that it is spawning above an astromine meteor

Modloader: fabric
Version: 1.16.3
Ars Theurgia version: arstheurgia-1.0.3.jar
Astromine version: astromine-1.11.4+fabric-1.16.3.jar
java version: 8

**Comment by ymndoseijin** [comment]
Should be fixed now with the new release (1.0.5). Will close the issue now.
